name: Deploy .NET API + React Client to Azure

on:
  push:
    branches:
      - main  # Or whatever your default branch is

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore 

    - name: Build API project
      run: dotnet build --configuration Release --no-restore

    - name: Publish API (with React)
      run: dotnet publish API/API.csproj -c Release -o publish_output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: movies-to-watch-app-danwright
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish_output
