name: Deploy .NET API + React Client to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install React dependencies
      working-directory: client
      run: npm install

    - name: Build React app
      working-directory: client
      run: npm run build

    - name: Copy React build to API wwwroot
      run: |
        rm -rf API/wwwroot
        cp -r client/dist API/wwwroot

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build API project
      run: dotnet build API/API.csproj --configuration Release --no-restore

    - name: Publish API project
      run: dotnet publish API/API.csproj --configuration Release --output publish_output

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: movies-to-watch-app-danwright
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish_output
